# Generated by Django 5.1.4 on 2024-12-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0005_alter_membershipplan_access_level_membershippurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gympro.membershipplan'),
        ),
    ]
