# Generated by Django 5.1.4 on 2024-12-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0006_alter_member_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippurchase',
            name='active',
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='end_date',
            field=models.DateField(blank=True, help_text='Narystės galiojimo pabaiga', null=True),
        ),
    ]
