# Generated by Django 5.1.4 on 2025-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0008_alter_class_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
