# Generated by Django 5.1.4 on 2025-01-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0009_instructor_facebook_instructor_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration',
        ),
    ]
