# Generated by Django 5.1.4 on 2025-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0010_remove_membershipplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membership_logos/'),
        ),
    ]
