# Generated by Django 5.1.4 on 2025-01-06 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0011_membershipplan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Įveskite pamokos datą ir laiką.'),
        ),
    ]
