# Generated by Django 5.1.4 on 2025-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro', '0012_alter_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('dziudo', 'Dziudo'), ('jiu-jitsu', 'Jiu-jitsu'), ('karate', 'Karate'), ('boksas', 'Boksas'), ('thai-boksas', 'Thai-Boksas'), ('crossfit', 'CrossFit'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('zumba', 'Zumba'), ('fitness', 'Fitness'), ('dance', 'Dance')], max_length=50),
        ),
    ]
